language: node_js

node_js:
- node

notifications:
  email: false

script:
- make

before_deploy:
- ./scripts/package.sh

deploy:
- provider: s3
  access_key_id: $S3_ACCESS_KEY
  secret_access_key: $S3_ACCESS_SECRET
  bucket: rschmidmeister
  region: nyc3
  endpoint: https://nyc3.digitaloceanspaces.com
  skip_cleanup: true

  local_dir: dist
  upload-dir: travis-builds/mdl-app
  acl: public_read

  on:
    repo: bash/mdl-app
    branch: master

  edge:
    branch: ha-s3-endpoint

after_deploy:
- curl -X POST -H "Authorization: Token travis:$TOBY_SECRET" http://toby.rubys.ninja:8629/v1/jobs/mdl-app
